# サイト全体の基本設定
title: "ExcelとRで学ぶビジネスデータサイエンス入門 ― サポートサイト"
description: "『ExcelとRで学ぶビジネスデータサイエンス入門』（講談社サイエンティフィク）の読者向けに、データ、Rスクリプト、訂正情報・補足資料などを公開します。"
theme: minima

# 公開URL（GitHub Pages）
url: "https://yyosh.github.io"
baseurl: "/business-data-science-excel-r"

# ヘッダーに表示するページ
header_pages:
  - index.md
  - data/README.md
  - scripts/README.md
  - docs/README.md
  - publisher.md     # ← 出版社ページへのリンク（内部ページ）

# エンコーディング
encoding: "utf-8"

# Markdownエンジン設定
markdown: kramdown
kramdown:
  input: GFM

# サイトの見た目調整（オプション）
show_excerpts: true
permalink: pretty
timezone: Asia/Tokyo

include:
  - assets/css/style.css

