title: "ExcelとRで学ぶビジネスデータサイエンス入門 ― サポートサイト"
description: "『ExcelとRで学ぶビジネスデータサイエンス入門』（講談社サイエンティフィク）の読者向け補足資料・データ・Rスクリプトを公開するサポートページです。"
theme: minima

# サイトの公開URL
url: "https://yyosh.github.io"
baseurl: "/business-data-science-excel-r"

# ヘッダーメニューに表示するページ
header_pages:
  - index.md
  - data/README.md
  - scripts/README.md
  - docs/README.md

# 日本語でも文字化けしないように
encoding: "utf-8"

# Markdown拡張機能
markdown: kramdown
kramdown:
  input: GFM
